### PR TITLE
Make the data conform to RandomAccessCollection

### PR DESCRIPTION
**Pull request by MojtabaHs**
It now supports the entire range of hashable collections, including arrays, ranges, sets, and more

### CODE REVIEW

**Review by gordan-glavas-codecons — APPROVED** [review]

**Comment by gordan-glavas-codecons** [comment]
Thanks for contributing!

**Comment by gordan-glavas-codecons** [comment]
@MojtabaHs Is there a reason why you set the Data.Element to conform to Hashable? It's not necessary for the library to work, and historically people have complained about this constraint.

**Comment by MojtabaHs** [comment]
> @MojtabaHs Is there a reason why you set the Data.Element to conform to Hashable? It's not necessary for the library to work, and historically people have complained about this constraint.

I think it is a leftover of my experiments with the enhancements I was going to apply to the library, like applying the pixel-perfect spacing instead of the current ambiguous padding which applies 2 spacings in between and on unintended at the sides of the layout.

I will double-check and take care of that in the next few PRs where I cleaned up and documented the code

**Comment by gordan-glavas-codecons** [comment]
> > @MojtabaHs Is there a reason why you set the Data.Element to conform to Hashable? It's not necessary for the library to work, and historically people have complained about this constraint.
> 
> I think it is a leftover of my experiments with the enhancements I was going to apply to the library, like applying the pixel-perfect spacing instead of the current ambiguous padding which applies 2 spacings in between and on unintended at the sides of the layout.
> 
> I will double-check and take care of that in the next few PRs where I cleaned up and documented the code

Thanks, I'll hold off on releasing a new version until that is sorted out.

**Comment by MojtabaHs** [comment]
> Thanks, I'll hold off on releasing a new version until that is sorted out.

I have done it in the PR #15 . Also rebased [the other PR](https://github.com/globulus/swiftui-flow-layout/pull/14) based on this change.

**Pull request merged**
